[package]
name = "fhe_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sunscreen = "*"
polyfit-rs = "0.2.0"
csv="*"
polynomial-ring = "0.4.7"
assert_approx_eq = "1.1.0"
bincode = "1.3.3"